### ISSUE TITLE
RE: NFC plugin is able to read a number of tags only

### ISSUE THREAD

**Issue by samliaw** [Telerik-Verified-Plugins/NFC#1]
I am developing an NFC application using Telerik-Verified-Plugins/NFC. The NFC application is able to read a number of tags but it is not able to detect other tags. The tags are of the same batch so they are identical. 

My problem is that the NFC application is able to read a small number of tags. When I use a native NFC application, it is able to read all tags with no problems. 

My question is does the hybrid NFC application has less capabilities than the native NFC application? 

thanks
Sam Liaw

**Comment by EddyVerbruggen** [comment]
Hi Sam,

When testing the plugin, do you use our demo app, or have you created your own test-app?

ALso, do you experience trouble on WP8 or Android devices?

Thanks,
Eddy

**Comment by samliaw** [comment]
Hi Eddy,

I try both the demo app and I create my own test-app. Both shows the same
behaviour. I am running on both android devices, Samsung note 3 and Sony
Z2.

I will see if my colleagues have WP8 phone.

thanks
Sam Liaw

**Comment by EddyVerbruggen** [comment]
Thanks for the feedback. Can you also tell me which Android versions your devices are running so I can test this on a similar device?

And perhaps even tell me which type of NFC tags you're using?

Thanks,
Eddy
