### ISSUE TITLE
Error in AppBuilder when building for Android

### ISSUE THREAD

**Issue by nicola-c** [Telerik-Verified-Plugins/NFC#3]
Hello,
I'm testing the plugin in a new project (Cordova 3.5.0). During compilation (Build for Android) AppBuilder hangs with a compile error. If I remove the plugin, compilation ends correctly. See attached file for error details.
I forgot some setting ?
Thanks
Nicola

https://dl.dropboxusercontent.com/u/7208407/NFC_Plugin_Error.txt

**Comment by EddyVerbruggen** [comment]
Yikes, nasty stacktrace. I just started an AppBuilder project with (only) the NFC plugin on Android 3.5.0 without errors. So it may be related to the combination of plugins you're using. Is there any chance I can get my hands on your project?

**Comment by nicola-c** [comment]
Hello Eddy,
see attached zip (I export from AppBuilder) . The application is for test, I removed some views, but remains the compilation error.
Many Thanks 
https://dl.dropboxusercontent.com/u/7208407/NFC_Test.zip

**Comment by EddyVerbruggen** [comment]
Hi @nicola-c version 0.6.1 fixes the problem, sorry it took so long for it to be available.

**Comment by nicola-c** [comment]
Hi @EddyVerbruggen . Many Thanks  and don't worry , I understand that we all are very busy ;-)
