### ISSUE TITLE
Adding this plugin breaks IOS

### ISSUE THREAD

**Issue by alindzon** [Telerik-Verified-Plugins/NFC#7]
I added this plugin, and my IOS version stopped working even with no programming at all added to the controllers etc...

Removed it, IOS version works again.

I need this for my Android app, but adding it in messes up IOS.  Is there a solution?
Can this be issue be fixed in the plugin itself?

**Comment by EddyVerbruggen** [comment]
You're the first to report it, can't find a similar issue on the upstream repo either. So please share your project so we have some more info. Also please share any errors you see.

**Comment by alindzon** [comment]
is there any code we can add into the plugin so it will add an empty file or nothing to the IOS version and not the js file that android needs?

I assume there is a way for different platforms to have different js files or something.  As I don't write plugins I have no clue, just assuming.

**Comment by EddyVerbruggen** [comment]
That's why I need to see your code and know where it crashes. What I usually do is check for an object like [this](https://github.com/Telerik-Verified-Plugins/NFC/blob/d4a8e4d2dcdb8ea854a4c4a6aa15eb7f2c6a7ac9/www/phonegap-nfc.js#L738) to exist.

**Comment by alindzon** [comment]
it is a large and complex app with tons of plugins.  What I did to figure out why it suddenly was not working on IOS was I removed completely recent plugins, and yours is the one that caused the issue.  The symptom is startup stuff does not fire, so my access to the local file system, which normally works crashes the app with an undefined error.  there is no code I am adding or removing, just removing or adding the NFC plugin alone breaks it.  I noticed many plugins have different files for IOS and Android.  I am thinking that might be the solution to prevent cordova from adding any code code at all from this plugin to the IOS version, does that make sense?

**Comment by EddyVerbruggen** [comment]
This is not my plugin, just trying to help here.

If I were you I'd start a new hello world app, add this plugin, and run it on iOS. If it doesn't crash it's a combination of your app and this plugin which I won't be able to assist with unless you share a project that clearly shows the problem.

**Comment by alindzon** [comment]
That is worth a shot.  With regard to my question, is there not a way to make a plugin have a different .js for ios, if we put an empty one there, would likely eliminate the situation.

**Comment by EddyVerbruggen** [comment]
Sure, fork the plugin, add an `<ios>` branch to plugin.xml and add something like [this](https://github.com/Telerik-Verified-Plugins/NFC/blob/d4a8e4d2dcdb8ea854a4c4a6aa15eb7f2c6a7ac9/plugin.xml#L18). However it's easier to check `if (window.nfc)`..

**Comment by alindzon** [comment]
So I wanted to look at the plugin again, and added it back, this time as the last plugin added, and no issue.  So I am now totally confused as to why removing it and putting it back in a different order, changed things.
